import type { CommitConfig } from './config.ts'
import { breakingPattern, capitalPattern, punctuationPattern, subjectPattern } from './commit.pattern.ts'

// Validates a commit subject against the conventional format.

export type Failure = {
  rule: string
  detail: string
}

export const subjectOf = (message: string): string => {
  const [first] = message.split('\n')

  return (first ?? '').trim()
}

export const validate = (message: string, config: CommitConfig): Failure[] => {
  const subject = subjectOf(message)
  const failures: Failure[] = []

  // A merge or revert subject is generated by git and is left alone.
  if (subject.startsWith('Merge ') || subject.startsWith('Revert ')) {
    return failures
  }

  // The marker only counts in the header, so a bang inside a description is left alone.
  if (breakingPattern.test(subject)) {
    failures.push({ rule: 'breaking', detail: 'a breaking change belongs in a BREAKING CHANGE footer' })

    return failures
  }

  const shape = subjectPattern.exec(subject)

  if (!shape) {
    failures.push({ rule: 'format', detail: 'a subject reads as type(scope): description' })

    return failures
  }

  const [, type, scope, description] = shape

  if (!type || !config.types.includes(type)) {
    failures.push({ rule: 'type', detail: `type must be one of ${config.types.join(', ')}` })
  }

  // An empty scope list accepts any scope, so a project that names none is not forced to enumerate them.
  if (scope && config.scopes.length > 0 && !config.scopes.includes(scope)) {
    failures.push({ rule: 'scope', detail: `scope must be one of ${config.scopes.join(', ')}` })
  }

  if (description && capitalPattern.test(description)) {
    failures.push({ rule: 'case', detail: 'a description starts with a lowercase letter' })
  }

  if (description && punctuationPattern.test(description)) {
    failures.push({ rule: 'punctuation', detail: 'a description ends without punctuation' })
  }

  if (subject.length > config.maxLength) {
    failures.push({ rule: 'length', detail: `a subject fits within ${config.maxLength} characters` })
  }

  return failures
}
