/**
 * Validates a commit subject against the Conventional Commits format.
 *
 * A subject reads as `type(scope): description`, where the type comes from a
 * configured vocabulary, the scope is optional, and the description starts
 * lowercase and ends without punctuation.
 *
 * This module departs from Conventional Commits in one way: the `!` breaking
 * change marker is rejected rather than accepted. A breaking change is
 * declared with a `BREAKING CHANGE:` footer in the commit body instead.
 *
 * Only the first line of a message is examined. Merge and revert subjects are
 * generated by git and pass without inspection.
 *
 * @example
 * ```ts
 * import { validate } from '@whaaaley/git-going/validator'
 * import { defaults } from '@whaaaley/git-going/config'
 *
 * validate('feat(api): add pagination', defaults.commit) // []
 * validate('Feat: Add Pagination.', defaults.commit) // several failures
 * ```
 *
 * @module
 */

import type { CommitConfig } from './config.ts'
import { breakingPattern, capitalPattern, punctuationPattern, subjectPattern } from './commit.pattern.ts'

/**
 * A single broken rule, as reported by {@link validate}.
 *
 * `rule` is a stable identifier a caller can branch on, one of `breaking`,
 * `format`, `type`, `scope`, `case`, `punctuation`, or `length`. `detail` is a
 * human readable sentence describing what the subject should have looked like,
 * suitable for printing straight to a terminal.
 */
export type Failure = {
  rule: string
  detail: string
}

/**
 * Extracts the subject line from a full commit message.
 *
 * The subject is the first line, trimmed. Everything after the first newline
 * is the body and is ignored.
 *
 * @example
 * ```ts
 * subjectOf('feat: add pagination\n\nBREAKING CHANGE: drops v1') // 'feat: add pagination'
 * ```
 */
export const subjectOf = (message: string): string => {
  const [first] = message.split('\n')

  return (first ?? '').trim()
}

/**
 * Checks a commit message against the conventional format and the configured
 * vocabulary.
 *
 * Every rule is evaluated, so a subject that breaks several returns several
 * failures. Two cases short circuit and return a single failure on their own:
 * a `!` breaking change marker in the header, and a subject that does not
 * parse as `type(scope): description` at all.
 *
 * A merge or revert subject returns no failures without being inspected.
 *
 * @param message The full commit message. Only its first line is examined.
 * @param config The permitted types and scopes, and the maximum subject length. An empty `scopes` list accepts any scope.
 * @returns Every broken rule, or an empty array when the subject passes.
 *
 * @example
 * ```ts
 * const failures = validate('Fix: Broken.', defaults.commit)
 *
 * for (const failure of failures) {
 *   console.error(`${failure.rule}: ${failure.detail}`)
 * }
 * ```
 */
export const validate = (message: string, config: CommitConfig): Failure[] => {
  const subject = subjectOf(message)
  const failures: Failure[] = []

  if (subject.startsWith('Merge ') || subject.startsWith('Revert ')) {
    return failures
  }

  // The pattern is header-scoped, so a bang inside a description is left alone.
  if (breakingPattern.test(subject)) {
    failures.push({ rule: 'breaking', detail: 'a breaking change belongs in a BREAKING CHANGE footer' })

    return failures
  }

  const shape = subjectPattern.exec(subject)

  if (!shape) {
    failures.push({ rule: 'format', detail: 'a subject reads as type(scope): description' })

    return failures
  }

  const [, type, scope, description] = shape

  if (!type || !config.types.includes(type)) {
    failures.push({ rule: 'type', detail: `type must be one of ${config.types.join(', ')}` })
  }

  // An empty scope list accepts any scope, so a project that names none is not forced to enumerate them.
  if (scope && config.scopes.length > 0 && !config.scopes.includes(scope)) {
    failures.push({ rule: 'scope', detail: `scope must be one of ${config.scopes.join(', ')}` })
  }

  if (description && capitalPattern.test(description)) {
    failures.push({ rule: 'case', detail: 'a description starts with a lowercase letter' })
  }

  if (description && punctuationPattern.test(description)) {
    failures.push({ rule: 'punctuation', detail: 'a description ends without punctuation' })
  }

  if (subject.length > config.maxLength) {
    failures.push({ rule: 'length', detail: `a subject fits within ${config.maxLength} characters` })
  }

  return failures
}
